services:
  backend:
    container_name: backend
    build: ./Backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - FRONTEND=http://frontend:80
    volumes:
      - ./Backend:/app
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_BASE_URL=http://backend:8000
    restart: always
